# Generated by Django 5.1.3 on 2026-04-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='category',
            field=models.CharField(choices=[('pre_crop', 'Pre-Crop Scheme'), ('crop_loss', 'Crop Loss Support')], default='pre_crop', max_length=20),
        ),
    ]
