# Generated by Django 5.1.3 on 2026-04-25 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_scheme_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='api.crop')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('crop', 'date')},
            },
        ),
    ]
